[book]
authors = ["anupama-pathirage"]
language = "en"
multilingual = false
src = "src"
title = "Ballerina Best Practices Guide"


[output.html]
theme = "mytheme"
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/learn-ballerina/learn-ballerina.github.io"

[output.html.fold]
enable = true