name: Test Samples

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  test:
    env:
      JBAL_VERSION: swan-lake-beta6
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2
    - name: Download jBallerina deb
      run: |
          curl -L "https://github.com/ballerina-platform/ballerina-distribution/releases/download/v$JBAL_VERSION/ballerina-linux-installer-x64-$JBAL_VERSION.deb" > $HOME/ballerina-linux-installer-x64-$JBAL_VERSION.deb
    - name: Install jBallerina deb
      run: |
        sudo dpkg -i $HOME/ballerina-linux-installer-x64-$JBAL_VERSION.deb
        echo "/usr/lib/ballerina/bin" >> $GITHUB_PATH
        echo "/usr/lib/ballerina/dependencies/jdk-11.0.8+10-jre/bin/java" >> $GITHUB_PATH
    - name: Run Tests
      run: |
        bash ./code/test.sh